Repository react-project-team4/ReactProjectTeam4, pull requests merged in 2023-11, with the labels that each got.

#10 fix header, main, footer css 모듈화
  db.json
  package.json
  src/App.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Main.js
  src/components/ShowProduct.js
  src/css/footer.module.css
  src/css/header.module.css
  src/css/main.module.css
Labels: 🐞 BugFix

#12 Html&css: bootstrap+noonnu font 적용
  package-lock.json
  package.json
  src/App.js
  src/assets/scss/main.scss
  src/components/ShowProduct.js
  src/css/header.module.css
  src/fonts/DNFBitBitv2.otf
  src/fonts/DNFBitBitv2.otf:Zone.Identifier
  src/index.css
  src/index.js
Labels: 🎨 Html&css

#13 feat: create front-end back-end folder
  src/App.js
  src/fonts/DNFBitBitv2.otf:Zone.Identifier
  src/front-end/assets/scss/main.scss
  src/front-end/components/Footer.js
  src/front-end/components/Header.js
  src/front-end/components/Main.js
  src/front-end/components/ProductList.js
  src/front-end/components/ProductRegister.js
  src/front-end/components/ShowProduct.js
  src/front-end/css/footer.module.css
  src/front-end/css/header.module.css
  src/front-end/css/main.module.css
  src/front-end/css/productList.module.css
  src/front-end/fonts/DNFBitBitv2.otf
  src/index.js
Labels: 📃 Docs

#14 font 적용 테스트
  src/index.css
  src/index.js
Labels: 🎨 Html&css

#15 font 적용
  src/index.css
Labels: 🎨 Html&css

#16 fix: header 새로고침 문제 해결
  src/App.js
  src/front-end/assets/scss/main.scss
  src/front-end/components/CreateProduct.js
  src/front-end/components/Header.js
  src/front-end/components/ProductList.js
  src/front-end/components/ProductRegister.js
  src/front-end/css/productList.module.css
  src/index.js
Labels: 🐞 BugFix

#17 ✨ feat : 상품 이미지 S3업로드 구현 및 상품 상세보기 이동 Link 생성
  db.json
  package-lock.json
  package.json
  src/App.jsx
  src/back-end/services/aws.js
  src/front-end/components/CreateProduct.js
  src/front-end/components/CreateProduct.jsx
  src/front-end/components/Footer.jsx
  src/front-end/components/Header.jsx
  src/front-end/components/InputImage.jsx
  src/front-end/components/Main.jsx
  src/front-end/components/ProductCard.jsx
  src/front-end/components/ProductList.js
  src/front-end/components/ProductList.jsx
  src/front-end/components/ShowProduct.js
  src/front-end/imgs/xImage.png
  src/index.jsx
Labels: ✨ Feature, 📬 API

#18 feat: 제품상세보기
  db.json
  src/App.jsx
  src/front-end/components/Header.jsx
  src/front-end/components/ShowProduct.jsx
  src/index.jsx
Labels: ✨ Feature

#19 fix: 페이지 이동 시 정보 전달 오류 해결
  db.json
  src/App.jsx
  src/front-end/components/ProductCard.jsx
  src/front-end/components/ShowProduct.js
  src/front-end/components/ShowProduct.jsx
Labels: 🐞 BugFix

#20 Develop
  adsf.md
  db.json
  src/App.jsx
  src/front-end/components/Login.jsx
  src/front-end/components/Register.jsx
  src/front-end/css/Register.css
  src/index.jsx
Labels: ✨ Feature

#21 fix:로그인 회원가입 수정
  src/App.jsx
  src/front-end/components/Login.jsx
  src/front-end/components/Register.jsx
  src/front-end/css/Register.module.css
  src/index.jsx
Labels: 🐞 BugFix, 🎨 Html&css

#22 fix:db.json 수정
  db.json
Labels: 🐞 BugFix, 📃 Docs

#23 ✨ feat: 배경사진 삽입 및 상품등록 및 css조정
  db.json
  src/App.jsx
  src/front-end/components/CreateProduct.jsx
  src/front-end/components/Footer.jsx
  src/front-end/components/Header.jsx
  src/front-end/components/ProductCard.jsx
  src/front-end/components/ProductList.jsx
  src/front-end/css/createProduct.module.css
  src/front-end/css/footer.module.css
  src/front-end/css/header.module.css
  src/front-end/css/main.module.css
  src/front-end/css/productList.module.css
  src/front-end/imgs/fukuokaMark.png
  src/front-end/imgs/sakura.jpg
  src/index.css
  src/index.jsx
Labels: 🎨 Html&css, ✨ Feature

#24 ✨ feat : 회원가입 페이지 수정 및 로그인 시 정보가 로컬스토리지에저장
  db.json
  src/front-end/components/Login.jsx
  src/front-end/components/Register.jsx
  src/front-end/css/Register.module.css
Labels: ✨ Feature

#26 test: 로그인 후 헤더 동작
  db.json
  src/App.jsx
  src/back-end/services/aws.js
  src/front-end/components/Header.jsx
  src/front-end/components/Login.jsx
  src/front-end/components/MypageComponents/CreateAddressModal.jsx
  src/front-end/components/MypageComponents/MyPage.jsx
  src/front-end/components/MypageComponents/MyPageAddressChange.jsx
  src/front-end/components/MypageComponents/MyPageEditPrivacy.jsx
  src/front-end/components/MypageComponents/MyPageOrderList.jsx
  src/front-end/components/ProductList.jsx
  src/front-end/components/ShowProduct.jsx
  src/front-end/css/MyPageCss/MyPage.module.css
  src/front-end/css/MyPageCss/MyPageAddressChange.module.css
  src/front-end/css/MyPageCss/MyPageOrderList.module.css
  src/front-end/css/Register.module.css
Labels: ✨ Feature

#28 🔨 chore: folder 이름 소문자로 변경 및 component folder 구분 작업
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/front-end/components/Footer.jsx
  src/front-end/components/Login.jsx
  src/front-end/components/Main.jsx
  src/front-end/components/MypageComponents/MyPageOrderList.jsx
  src/front-end/components/Register.jsx
  src/front-end/components/mainComponents/Main.jsx
  src/front-end/components/mainComponents/MultyCarousel.jsx
  src/front-end/components/mypageComponents/CreateAddressModal.jsx
  src/front-end/components/mypageComponents/MyPage.jsx
  src/front-end/components/mypageComponents/MyPageAddressChange.jsx
  src/front-end/components/mypageComponents/MyPageEditPrivacy.jsx
  src/front-end/components/mypageComponents/MyPageOrderList.jsx
  src/front-end/components/productListComponents/CreateProduct.jsx
  src/front-end/components/productListComponents/InputImage.jsx
  src/front-end/components/productListComponents/ProductCard.jsx
  src/front-end/components/productListComponents/ProductList.jsx
  src/front-end/css/app.module.css
  src/front-end/css/footer.module.css
  src/front-end/css/mainCss/main.module.css
  src/front-end/css/mainCss/multyCarousel.module.css
  src/front-end/css/myPageCss/MyPage.module.css
  src/front-end/css/myPageCss/MyPageAddressChange.module.css
  src/front-end/css/myPageCss/MyPageOrderList.module.css
  src/front-end/css/productCss/createProduct.module.css
  src/front-end/css/productCss/productList.module.css
  src/index.css
  src/index.jsx
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#29 Develop
  db.json
  public/index.html
  src/front-end/components/AdminPage.jsx
  src/front-end/components/Header.jsx
Labels: ✨ Feature

#30 fetch
  db.json
  src/front-end/components/Header.jsx
Labels: ✨ Feature

#31 🐛fix: db.json 수정에 따른 제품상세보기 오류 수정
  adsf.md
  db.json
  package-lock.json
  package.json
  src/App.jsx
  src/front-end/components/Header.jsx
  src/front-end/components/ShowProduct.jsx
  src/front-end/css/app.module.css
  src/front-end/css/productCss/showProduct.module.css
Labels: 🐞 BugFix

#32 🐛fix: 병합 에러 수정
  src/front-end/components/Header.jsx
Labels: 🐞 BugFix

#34 🐛fix: 새로고침시 헤더 오류 수정
  src/App.jsx
  src/front-end/components/Comment.jsx
  src/front-end/components/Header.jsx
  src/front-end/components/ShowProduct.jsx
Labels: 🐞 BugFix

#35 ✨ logout
  db.json
  src/App.jsx
  src/front-end/components/Header.jsx
Labels: ✨ Feature

#37 ✨ feat : productList 페이지에서 간편삭제 구현 S3에서 이미지 삭제 구현
  .gitignore
  db.json
  src/App.jsx
  src/back-end/services/aws.js
  src/front-end/components/productListComponents/CreateProduct.jsx
  src/front-end/components/productListComponents/ProductCard.jsx
  src/front-end/components/productListComponents/ProductList.jsx
Labels: ✨ Feature

#39 🐛 fix : createProduct 고정된 아이디 사용 해제 및 db.json 불필요 데이터 삭제
  db.json
  src/front-end/components/mainComponents/MultyCarousel.jsx
  src/front-end/components/productListComponents/CreateProduct.jsx
  src/front-end/components/productListComponents/ProductCard.jsx
  src/front-end/components/productListComponents/ProductList.jsx
Labels: 🐞 BugFix, 🔨 Refactor

#40 🐛fix: 상품리스트가 비어있을 시 에러 수정
  src/front-end/components/Comment.jsx
  src/front-end/components/ShowProduct.jsx
Labels: 🐞 BugFix

#41 ✨ feat : 비밀번호 암호화
  db.json
  package-lock.json
  package.json
  src/front-end/components/Login.jsx
  src/front-end/components/Register.jsx
Labels: ✨ Feature

#42 🔨 chore : ShowProduct.jsx content output 개행되게 수정
  db.json
  src/front-end/components/ShowProduct.jsx
  src/front-end/components/productListComponents/ProductCard.jsx
  src/front-end/components/productListComponents/ProductList.jsx
Labels: ✨ Feature
